### ISSUE TITLE
Need compile options in TemplateProvider for Template Inheritance (extends or include)

### ISSUE THREAD

**Issue by mansurg** [catberry/catberry-jade#1]
I got following an error when trying Inheritance:
>the "filename" option is required to use "include" with "relative" paths] path: undefined
>the "basedir" option is required to use "extends" with "absolute" paths] path: undefined

**Comment by pragmadash** [comment]
There is no way to use Jade inheritance in Catberry's template provider.
Every Catberry's component is isolated from others and one template can not have reference to another.

Could you describe a case when you need the inheritance using cat-components?

**Comment by mansurg** [comment]
I want dynamically change page theme or page layout by user action and depending on page.

**Comment by pragmadash** [comment]
Ok, you can change active component with another one which has a different layout. For example, you can do it using condition statement.

Unfortunately, using Catberry component-based architecture you can not use template inheritance. You can only inherit component logic or store.

**Comment by mansurg** [comment]
I implemented what I wanted by using Dust (look at this: https://github.com/mansurg/CatHouse). I trying to do the same using Jade (https://github.com/mansurg/CatHouse/tree/jade-version), but I had to do some changes in catberry-jade (https://github.com/mansurg/catberry-jade/commit/065c6a005c28c7cb91a14c7f08af533824c41443 What do you think of this implementation?). Unfortunately Jade not supported dynamic template inheritance by analogy with dynamic partials in Dust. I decided to stay on Dust.

**Comment by pragmadash** [comment]
@mansurg Great solution for Jade! But I think it would be better if we inject config section called `jadeOptions`, not just a `baseDir`. Pull request is welcome!
