### ISSUE TITLE
catberry-jade error with debug-mode

### ISSUE THREAD

**Issue by prozbik** [catberry/catberry-jade#4]
Hello , iam using jade-template, and when i try run npm run debug, i have an error, that program cant find runtime.js.

So i go to node_modules/catberry-jade/package.json and change 
```
  "browser": {
    "./lib/TemplateProvider.js": "./browser/TemplateProvider.js",
    "jade": "../jade/runtime.js" <= this part
  },

```

**Comment by pragmadash** [comment]
Hi @prozbik, could you please post a PR for that? Have you checked the changes, does any project work with those changes?

**Comment by prozbik** [comment]
My actions:
catberry init empty-jade
npm install --production
npm run debug
error
![catberrybug](https://cloud.githubusercontent.com/assets/10572181/13217288/177bb988-d96a-11e5-964a-efe3a95159d0.png)

if type npm run debug-win, error wil be the same, but server will lifted up.

**Comment by pragmadash** [comment]
Resolved by the release https://github.com/catberry/catberry-jade/releases/tag/2.0.1
